### ISSUE TITLE
Support for attachments

### ISSUE THREAD

**Issue by samhstn** [ex-aws/ex_aws_ses#2]
I would like the ability to be able to attach a file when I send an email.

`ex_aws_ses` currently doesn't facilitate this (https://github.com/ex-aws/ex_aws_ses/search?utf8=%E2%9C%93&q=attachments&type=).

Would this improvement make sense to be included as a `send_email_opt` in the `send_email` function here: https://github.com/ex-aws/ex_aws_ses/blob/master/lib/ex_aws/ses.ex#L65?

**Comment by benwilson512** [comment]
As with the other ExAws libraries, the general goal here is to simply expose the AWS API operations. As far as I can tell the only API operation that supports attachments on SES is https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html which we use at Cargosense quite successfully to send attachments. It isn't possible however to expose an `attachments` option here since that needs to be handled by whatever library you use to encode the email.

**Comment by samhstn** [comment]
@benwilson512 thank you for the fast response. Given that we can't expose an attachments option here, would it perhaps be beneficial to include an example for how to attach files to emails, or would it be best to just close this issue?

**Comment by eboswort** [comment]
@benwilson512 If it's possible for you to share an example of using send raw email to send an email with an attachment that would be super helpful for me as well. 
You mention using a library to encode emails. Is there one you are using along with ex_aws_ses to encode those attachments?

**Comment by benwilson512** [comment]
I use `Mailman.Render.render` to render `%Mailman.Email{}` structs into raw SMTP, and then I pass that to ExAws.SES.

The challenge for writing an example here is that the examples will all vary pretty wildly depending on your preferred mail rendering library.

**Comment by eboswort** [comment]
Thanks! I'll check out Mailman
